# Generated by Django 5.1.1 on 2024-09-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_owner_item_user_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
