# Generated by Django 5.1.1 on 2024-09-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_item_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
