# Generated by Django 5.1.1 on 2024-09-23 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
