# Generated by Django 5.1.1 on 2024-09-23 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_item_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlistItem', to=settings.AUTH_USER_MODEL),
        ),
    ]
