# Generated by Django 5.1.1 on 2024-09-26 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_item_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='starting_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_bid_item', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='item',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlistItem', to=settings.AUTH_USER_MODEL),
        ),
    ]
