# Generated by Django 5.1.1 on 2024-09-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_item_starting_bid_alter_item_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='item',
        ),
    ]
